name = "MembraneRegistry"
uuid = "a1e72545-5e55-4276-afba-a441a557fcb5"
repo = "https://github.com/Boxylmer/MembraneRegistry"
description = ""

[packages]
11a4bec2-2c27-4554-8fe6-a2de72ffe064 = { name = "MembraneEOS", path = "M/MembraneEOS" }
1f25b7cf-f23e-4d96-9cc8-529206d1bcdc = { name = "GroupContribution", path = "G/GroupContribution" }
44adabc6-386d-4db0-bb6e-0f7b06129544 = { name = "SorptionModels", path = "S/SorptionModels" }
74801b09-e2e4-4a34-8eef-872f1277eff9 = { name = "DilationApparatus", path = "D/DilationApparatus" }
a9449b16-1c3f-48ab-aa2c-0b9c6d97beee = { name = "MembraneBase", path = "M/MembraneBase" }
c53a909a-c477-4ff1-81c4-bc1440289f4f = { name = "SorptionApparatus", path = "S/SorptionApparatus" }
c833957c-4f51-4127-86d5-ee4440407064 = { name = "GasSorptionApparatusGUI", path = "G/GasSorptionApparatusGUI" }
