name = "MembraneRegistry"
uuid = "2cf55aa6-a687-4bcb-b64d-02383cf66641"
repo = "https://github.com/Boxylmer/MembraneRegistry.git"

[packages]
a9449b16-1c3f-48ab-aa2c-0b9c6d97beee = { name = "MembraneUtils", path = "M/MembraneUtils" }
