name = "MembraneRegistry"
uuid = "a1e72545-5e55-4276-afba-a441a557fcb5"
repo = "https://github.com/Boxylmer/MembraneRegistry"
description = ""

[packages]
a9449b16-1c3f-48ab-aa2c-0b9c6d97beee = { name = "MembraneBase", path = "M/MembraneBase" }
